name: heroku_deploy
on:
  push:
jobs:
  example:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      run: |-
        if [[ $(command -v heroku) == "" ]]; then
          curl https://cli-assets.heroku.com/install.sh | sh
        else
          echo "Heroku is already installed. No operation was performed."
        fi
    - shell: bash
      env:
        API_KEY_NAME: HEROKU_API_KEY
        BRANCH: main
        TAG: "${{ github.ref }}"
        FORCE: true
        APP_NAME: gentle-lowlands-50246
      run: |-
        heroku maintenance:on --app ${{ env.APP_NAME }}
        if ${{ env.FORCE }};then
          force="-f"
        fi
        heroku_url="https://heroku:$${{ env.API_KEY_NAME }}@git.heroku.com/${{ env.APP_NAME }}.git"
        if [ -n "${{ env.BRANCH }}" ]; then
          git push $force $heroku_url ${{ env.BRANCH }}:main
        elif [ -n "${{ env.TAG }}" ]; then
          git push $force $heroku_url ${{ env.TAG }}^{}:main
        else
          echo "No branch or tag found."
          exit 1
        fi
        heroku maintenance:off --app ${{ env.APP_NAME }}
      timeout-minutes: 10

