name: deploy
on: workflow_dispatch
jobs:
  heroku_deploy-via-git:
    runs-on: ubuntu-latest
    env:
      MY_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
    - shell: bash
      run: |-
        if [[ $(command -v heroku) == "" ]]; then
          curl https://cli-assets.heroku.com/install.sh | sh
        else
          echo "Heroku is already installed. No operation was performed."
        fi
    - shell: bash
      env:
        PRINT_WHOAMI: false
      run: |-
        if [[ $HEROKU_API_KEY == "" ]]; then
          echo "No Heroku API key set, please set the HEROKU_API_KEY environment variable."
          echo "This can be found by running the `heroku auth:token` command locally."
          exit 1
        else
          echo "Heroku API key found."
          if [[ $PRINT_WHOAMI == "true" ]]; then heroku auth:whoami; fi
        fi
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: echo command-that-run-before-deploying
    - run: echo good to deploy
    - shell: bash
      env:
        API_KEY_NAME: MY_KEY
        BRANCH: main
        TAG: v1
        FORCE: false
        APP_NAME: gentle-lowlands-50246
      run: |-
        if ${{ env.FORCE }};then
          force="-f"
        fi
        heroku_url="https://heroku:$${{ env.API_KEY_NAME }}@git.heroku.com/${{ env.APP_NAME }}.git"
        if [ -n "${{ env.BRANCH }}" ]; then
          git push $force $heroku_url ${{ env.BRANCH }}:main
        elif [ -n "${{ env.TAG }}" ]; then
          git push $force $heroku_url ${{ env.TAG }}^{}:main
        else
          echo "No branch or tag found."
          exit 1
        fi
      timeout-minutes: 10
    - run: |
        echo running your-database-migration-command
        echo Done!
